#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Tue Nov 20 22:39:06 2018
#

import wx
import wx.adv
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 600))
        self.list_box_1 = wx.ListBox(self, wx.ID_ANY, choices=[""])
        self.combo_box_1 = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.combo_box_2 = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.datepicker_ctrl_1 = wx.adv.DatePickerCtrl(self, wx.ID_ANY)
        self.grd_spaces = wx.grid.Grid( self, wx.ID_ANY, size=(1, 1) )
        self.button_2 = wx.Button(self, wx.ID_ANY, "button_2")
        self.button_3 = wx.Button(self, wx.ID_ANY, "button_3")
        self.button_4 = wx.Button(self, wx.ID_ANY, "button_4")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("SpaceReport")
        self.SetBackgroundColour(wx.Colour(172, 172, 172))
        self.grd_spaces.CreateGrid( 10, 4 )
        self.grd_spaces.SetSelectionMode( wx.grid.Grid.SelectRows )
        self.grd_spaces.SetColLabelValue( 0, "Local" )
        self.grd_spaces.SetColSize( 0, 135 )
        self.grd_spaces.SetColLabelValue( 1, "Local Allo" )
        self.grd_spaces.SetColSize( 1, 128 )
        self.grd_spaces.SetColLabelValue( 2, "Trans" )
        self.grd_spaces.SetColSize( 2, 149 )
        self.grd_spaces.SetColLabelValue( 3, "Trans Allo" )
        self.grd_spaces.SetColSize( 3, 170 )
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Last Loading Port"), wx.HORIZONTAL)
        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Last Loading Port"), wx.HORIZONTAL)
        sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "SVVD"), wx.HORIZONTAL)
        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "List of Services"), wx.HORIZONTAL)
        sizer_5.Add(self.list_box_1, 2, wx.ALL | wx.EXPAND, 0)
        sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_7.Add(self.combo_box_1, 1, wx.ALL | wx.EXPAND, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_8.Add(self.combo_box_2, 1, wx.ALL | wx.EXPAND, 0)
        sizer_6.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_9.Add(self.datepicker_ctrl_1, 1, wx.ALL | wx.EXPAND, 0)
        sizer_6.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_4.Add( self.grd_spaces, 1, wx.EXPAND, 0 )
        sizer_2.Add(sizer_4, 8, wx.EXPAND, 0)
        sizer_3.Add((150, 10), 0, 0, 0)
        sizer_3.Add(self.button_2, 0, wx.ALL, 20)
        sizer_3.Add(self.button_3, 0, wx.ALL, 20)
        sizer_3.Add(self.button_4, 0, wx.ALL, 20)
        sizer_3.Add((150, 10), 0, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 8, wx.ALL | wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MyFrame

class SpaceReport(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class SpaceReport

if __name__ == "__main__":
    SpaceManagement = SpaceReport(0)
    SpaceManagement.MainLoop()
